/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GuestImport } from './routes/_guest'
import { Route as AuthImport } from './routes/_auth'
import { Route as GuestIndexImport } from './routes/_guest/index'
import { Route as GuestAboutImport } from './routes/_guest/about'
import { Route as GuestSubscriptionsImport } from './routes/_guest/Subscriptions'
import { Route as GuestRegisterImport } from './routes/_guest/Register'
import { Route as GuestLoginImport } from './routes/_guest/Login'
import { Route as AuthAdminImport } from './routes/_auth/_admin'
import { Route as AuthUploaderImport } from './routes/_auth/Uploader'
import { Route as AuthTeamImport } from './routes/_auth/Team'
import { Route as AuthStatisticsImport } from './routes/_auth/Statistics'
import { Route as AuthAdminAdminMyAdminImport } from './routes/_auth/_admin/admin/MyAdmin'
import { Route as AuthAdminAdminAccountsImport } from './routes/_auth/_admin/admin/Accounts'

// Create/Update Routes

const GuestRoute = GuestImport.update({
  id: '/_guest',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const GuestIndexRoute = GuestIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRoute,
} as any)

const GuestAboutRoute = GuestAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => GuestRoute,
} as any)

const GuestSubscriptionsRoute = GuestSubscriptionsImport.update({
  id: '/Subscriptions',
  path: '/Subscriptions',
  getParentRoute: () => GuestRoute,
} as any)

const GuestRegisterRoute = GuestRegisterImport.update({
  id: '/Register',
  path: '/Register',
  getParentRoute: () => GuestRoute,
} as any)

const GuestLoginRoute = GuestLoginImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => GuestRoute,
} as any)

const AuthAdminRoute = AuthAdminImport.update({
  id: '/_admin',
  getParentRoute: () => AuthRoute,
} as any)

const AuthUploaderRoute = AuthUploaderImport.update({
  id: '/Uploader',
  path: '/Uploader',
  getParentRoute: () => AuthRoute,
} as any)

const AuthTeamRoute = AuthTeamImport.update({
  id: '/Team',
  path: '/Team',
  getParentRoute: () => AuthRoute,
} as any)

const AuthStatisticsRoute = AuthStatisticsImport.update({
  id: '/Statistics',
  path: '/Statistics',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAdminAdminMyAdminRoute = AuthAdminAdminMyAdminImport.update({
  id: '/admin/MyAdmin',
  path: '/admin/MyAdmin',
  getParentRoute: () => AuthAdminRoute,
} as any)

const AuthAdminAdminAccountsRoute = AuthAdminAdminAccountsImport.update({
  id: '/admin/Accounts',
  path: '/admin/Accounts',
  getParentRoute: () => AuthAdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestImport
      parentRoute: typeof rootRoute
    }
    '/_auth/Statistics': {
      id: '/_auth/Statistics'
      path: '/Statistics'
      fullPath: '/Statistics'
      preLoaderRoute: typeof AuthStatisticsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/Team': {
      id: '/_auth/Team'
      path: '/Team'
      fullPath: '/Team'
      preLoaderRoute: typeof AuthTeamImport
      parentRoute: typeof AuthImport
    }
    '/_auth/Uploader': {
      id: '/_auth/Uploader'
      path: '/Uploader'
      fullPath: '/Uploader'
      preLoaderRoute: typeof AuthUploaderImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_admin': {
      id: '/_auth/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthAdminImport
      parentRoute: typeof AuthImport
    }
    '/_guest/Login': {
      id: '/_guest/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof GuestLoginImport
      parentRoute: typeof GuestImport
    }
    '/_guest/Register': {
      id: '/_guest/Register'
      path: '/Register'
      fullPath: '/Register'
      preLoaderRoute: typeof GuestRegisterImport
      parentRoute: typeof GuestImport
    }
    '/_guest/Subscriptions': {
      id: '/_guest/Subscriptions'
      path: '/Subscriptions'
      fullPath: '/Subscriptions'
      preLoaderRoute: typeof GuestSubscriptionsImport
      parentRoute: typeof GuestImport
    }
    '/_guest/about': {
      id: '/_guest/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof GuestAboutImport
      parentRoute: typeof GuestImport
    }
    '/_guest/': {
      id: '/_guest/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuestIndexImport
      parentRoute: typeof GuestImport
    }
    '/_auth/_admin/admin/Accounts': {
      id: '/_auth/_admin/admin/Accounts'
      path: '/admin/Accounts'
      fullPath: '/admin/Accounts'
      preLoaderRoute: typeof AuthAdminAdminAccountsImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/admin/MyAdmin': {
      id: '/_auth/_admin/admin/MyAdmin'
      path: '/admin/MyAdmin'
      fullPath: '/admin/MyAdmin'
      preLoaderRoute: typeof AuthAdminAdminMyAdminImport
      parentRoute: typeof AuthAdminImport
    }
  }
}

// Create and export the route tree

interface AuthAdminRouteChildren {
  AuthAdminAdminAccountsRoute: typeof AuthAdminAdminAccountsRoute
  AuthAdminAdminMyAdminRoute: typeof AuthAdminAdminMyAdminRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminAdminAccountsRoute: AuthAdminAdminAccountsRoute,
  AuthAdminAdminMyAdminRoute: AuthAdminAdminMyAdminRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthRouteChildren {
  AuthStatisticsRoute: typeof AuthStatisticsRoute
  AuthTeamRoute: typeof AuthTeamRoute
  AuthUploaderRoute: typeof AuthUploaderRoute
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthStatisticsRoute: AuthStatisticsRoute,
  AuthTeamRoute: AuthTeamRoute,
  AuthUploaderRoute: AuthUploaderRoute,
  AuthAdminRoute: AuthAdminRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
  GuestSubscriptionsRoute: typeof GuestSubscriptionsRoute
  GuestAboutRoute: typeof GuestAboutRoute
  GuestIndexRoute: typeof GuestIndexRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
  GuestSubscriptionsRoute: GuestSubscriptionsRoute,
  GuestAboutRoute: GuestAboutRoute,
  GuestIndexRoute: GuestIndexRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthAdminRouteWithChildren
  '/Statistics': typeof AuthStatisticsRoute
  '/Team': typeof AuthTeamRoute
  '/Uploader': typeof AuthUploaderRoute
  '/Login': typeof GuestLoginRoute
  '/Register': typeof GuestRegisterRoute
  '/Subscriptions': typeof GuestSubscriptionsRoute
  '/about': typeof GuestAboutRoute
  '/': typeof GuestIndexRoute
  '/admin/Accounts': typeof AuthAdminAdminAccountsRoute
  '/admin/MyAdmin': typeof AuthAdminAdminMyAdminRoute
}

export interface FileRoutesByTo {
  '': typeof AuthAdminRouteWithChildren
  '/Statistics': typeof AuthStatisticsRoute
  '/Team': typeof AuthTeamRoute
  '/Uploader': typeof AuthUploaderRoute
  '/Login': typeof GuestLoginRoute
  '/Register': typeof GuestRegisterRoute
  '/Subscriptions': typeof GuestSubscriptionsRoute
  '/about': typeof GuestAboutRoute
  '/': typeof GuestIndexRoute
  '/admin/Accounts': typeof AuthAdminAdminAccountsRoute
  '/admin/MyAdmin': typeof AuthAdminAdminMyAdminRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_auth/Statistics': typeof AuthStatisticsRoute
  '/_auth/Team': typeof AuthTeamRoute
  '/_auth/Uploader': typeof AuthUploaderRoute
  '/_auth/_admin': typeof AuthAdminRouteWithChildren
  '/_guest/Login': typeof GuestLoginRoute
  '/_guest/Register': typeof GuestRegisterRoute
  '/_guest/Subscriptions': typeof GuestSubscriptionsRoute
  '/_guest/about': typeof GuestAboutRoute
  '/_guest/': typeof GuestIndexRoute
  '/_auth/_admin/admin/Accounts': typeof AuthAdminAdminAccountsRoute
  '/_auth/_admin/admin/MyAdmin': typeof AuthAdminAdminMyAdminRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/Statistics'
    | '/Team'
    | '/Uploader'
    | '/Login'
    | '/Register'
    | '/Subscriptions'
    | '/about'
    | '/'
    | '/admin/Accounts'
    | '/admin/MyAdmin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/Statistics'
    | '/Team'
    | '/Uploader'
    | '/Login'
    | '/Register'
    | '/Subscriptions'
    | '/about'
    | '/'
    | '/admin/Accounts'
    | '/admin/MyAdmin'
  id:
    | '__root__'
    | '/_auth'
    | '/_guest'
    | '/_auth/Statistics'
    | '/_auth/Team'
    | '/_auth/Uploader'
    | '/_auth/_admin'
    | '/_guest/Login'
    | '/_guest/Register'
    | '/_guest/Subscriptions'
    | '/_guest/about'
    | '/_guest/'
    | '/_auth/_admin/admin/Accounts'
    | '/_auth/_admin/admin/MyAdmin'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_guest"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/Statistics",
        "/_auth/Team",
        "/_auth/Uploader",
        "/_auth/_admin"
      ]
    },
    "/_guest": {
      "filePath": "_guest.tsx",
      "children": [
        "/_guest/Login",
        "/_guest/Register",
        "/_guest/Subscriptions",
        "/_guest/about",
        "/_guest/"
      ]
    },
    "/_auth/Statistics": {
      "filePath": "_auth/Statistics.tsx",
      "parent": "/_auth"
    },
    "/_auth/Team": {
      "filePath": "_auth/Team.tsx",
      "parent": "/_auth"
    },
    "/_auth/Uploader": {
      "filePath": "_auth/Uploader.tsx",
      "parent": "/_auth"
    },
    "/_auth/_admin": {
      "filePath": "_auth/_admin.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_admin/admin/Accounts",
        "/_auth/_admin/admin/MyAdmin"
      ]
    },
    "/_guest/Login": {
      "filePath": "_guest/Login.tsx",
      "parent": "/_guest"
    },
    "/_guest/Register": {
      "filePath": "_guest/Register.tsx",
      "parent": "/_guest"
    },
    "/_guest/Subscriptions": {
      "filePath": "_guest/Subscriptions.tsx",
      "parent": "/_guest"
    },
    "/_guest/about": {
      "filePath": "_guest/about.tsx",
      "parent": "/_guest"
    },
    "/_guest/": {
      "filePath": "_guest/index.tsx",
      "parent": "/_guest"
    },
    "/_auth/_admin/admin/Accounts": {
      "filePath": "_auth/_admin/admin/Accounts.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/admin/MyAdmin": {
      "filePath": "_auth/_admin/admin/MyAdmin.tsx",
      "parent": "/_auth/_admin"
    }
  }
}
ROUTE_MANIFEST_END */
